[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
default_section = "THIRDPARTY"
known_first_party = "{{cookiecutter.project_slug}}"
known_django = "django"
known_wagtail = "wagtail"
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
line_length = 88
ensure_newline_before_comments = true
sections=["FUTURE","STDLIB","THIRDPARTY", "DJANGO", "WAGTAIL","FIRSTPARTY","LOCALFOLDER"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{cookiecutter.project_slug}}.settings"

[tool.coverage.run]
omit = ["*wsgi.py",
        "*asgi.py",
        "{{cookiecutter.project_slug}}/settings/**",
        "env/**"
        ]
